build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
    coverage:
      services:
        redislab-rejson:
          image: redislabs/rejson:1.0.4
          ports:
            - 6379
      tests:
        override:
          - command: ./vendor/bin/phpunit
            coverage:
              file: build/coverage.xml
              format: clover
    environment:
      php:
        version:  "7.2"
        pecl_extensions:
          - redis
filter:
  excluded_paths:
    - 'tests/*'
    - 'examples/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true